# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a chore name', max_length=200)),
                ('description', models.CharField(help_text='Enter description', max_length=500)),
                ('created_on', models.DateField()),
                ('deadline', models.DateField(help_text='When is this chore due?')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter an event name', max_length=200)),
                ('description', models.CharField(help_text='Enter description', max_length=500)),
                ('created_on', models.DateField()),
                ('deadline', models.DateField(help_text='When is this event going to occur?')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a forum name', max_length=200)),
                ('description', models.TextField(help_text='Enter a description for this forum', max_length=1000)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your Home Name', max_length=100)),
                ('address', models.CharField(help_text='Enter your Address', max_length=100, null=True)),
                ('leaseStart', models.DateTimeField(blank=True, null=True)),
                ('leaseEnds', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a post name', max_length=200)),
                ('content', models.CharField(help_text='Enter content', max_length=500)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a reminder name', max_length=200)),
                ('description', models.CharField(help_text='Enter description', max_length=500)),
                ('created_on', models.DateField()),
                ('deadline', models.DateField(help_text='When is this reminder due?')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a topic name', max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a transaction name', max_length=200)),
                ('description', models.CharField(help_text='Enter description', max_length=500)),
                ('created_on', models.DateField()),
                ('deadline', models.DateField(help_text='When is this transaction due?')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, help_text='Enter your password', max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Enter your phone number', max_length=10, null=True)),
                ('yog', models.CharField(blank=True, help_text='Enter your graduation date', max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('a', 'Admin'), ('u', 'User')], default='u', max_length=1)),
                ('status', models.TextField(help_text='Enter a status for others to view', max_length=1000)),
                ('bio', models.TextField(help_text='Enter a brief description of yourself', max_length=1000)),
                ('smokes', models.BooleanField(default=False, help_text='Do you smoke cigarettes?')),
                ('bedtime', models.TimeField(blank=True, help_text='What is your usual sleep-time?', null=True)),
                ('lastSeen', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(help_text='Enter your email', max_length=254)),
                ('pet_allergies', models.NullBooleanField(help_text='Are you allergic to pets?')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doma.Home')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a village name', max_length=200)),
                ('forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doma.Forum')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_home', to='doma.Home')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doma.User'),
        ),
        migrations.AddField(
            model_name='topic',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doma.Forum'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_user', to='doma.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='doma.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op', to='doma.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doma.Topic'),
        ),
        migrations.AddField(
            model_name='home',
            name='createdBy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_creator', to='doma.User'),
        ),
        migrations.AddField(
            model_name='home',
            name='forum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doma.Forum'),
        ),
        migrations.AddField(
            model_name='home',
            name='village',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_village', to='doma.Village'),
        ),
        migrations.AddField(
            model_name='forum',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doma.User'),
        ),
    ]
