# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to='doma.User'),
        ),
    ]
