# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0004_auto_20171101_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doma.Village'),
        ),
    ]
