# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0005_auto_20171101_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='forum',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='doma.Forum'),
        ),
        migrations.AlterField(
            model_name='village',
            name='forum',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='doma.Forum'),
        ),
    ]
