# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0006_auto_20171101_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default='', help_text='Enter your review here', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doma.Forum'),
        ),
    ]
