# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0007_auto_20171101_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default='', help_text='Enter your review here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='doma.User'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter a brief description of yourself', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastSeen',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Enter your password', max_length=100, null=True),
        ),
    ]
