# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doma', '0008_auto_20171101_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Enter your phone number', max_length=10, null=True)),
                ('yog', models.CharField(blank=True, help_text='Enter your graduation date', max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('a', 'Admin'), ('u', 'User')], default='u', max_length=1)),
                ('status', models.TextField(help_text='Enter a status for others to view', max_length=1000)),
                ('bio', models.TextField(blank=True, help_text='Enter a brief description of yourself', max_length=1000)),
                ('smokes', models.BooleanField(default=False, help_text='Do you smoke cigarettes?')),
                ('bedtime', models.TimeField(blank=True, help_text='What is your usual sleep-time?', null=True)),
                ('lastSeen', models.DateField(null=True)),
                ('email', models.EmailField(blank=True, help_text='Enter your email', max_length=254)),
                ('pet_allergies', models.NullBooleanField(help_text='Are you allergic to pets?')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='home',
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forum_created_by', to='doma.Profile'),
        ),
        migrations.AlterField(
            model_name='home',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_created_by', to='doma.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op', to='doma.Profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_user', to='doma.Profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='doma.Profile'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doma.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doma.Home'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
