# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0012_profile_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='presence',
        ),
    ]
