# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0013_remove_profile_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='village',
        ),
        migrations.AlterField(
            model_name='home',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_created_by', to='doma.Profile'),
        ),
        migrations.AlterField(
            model_name='home',
            name='forum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doma.Forum'),
        ),
        migrations.AlterField(
            model_name='home',
            name='leaseEnds',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='leaseStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
