# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0016_auto_20171211_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='created_on',
        ),
    ]
