# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0017_remove_forum_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastSeen',
            field=models.DateTimeField(null=True),
        ),
    ]
