# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0018_auto_20171211_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('vacation', 'On Vacation')], default='online', help_text='Select a status for others to view', max_length=8),
        ),
    ]
