# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0020_auto_20171212_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
