# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0021_auto_20171212_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deadline',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When is this event going to end?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='home',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='doma.Home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When is this event going to start?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
