# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0022_auto_20171212_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='doma.Home'),
        ),
    ]
