# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0023_auto_20171212_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateField(help_text='When is this event going to end?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateField(help_text='When is this event going to start?'),
        ),
    ]
