# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doma', '0029_auto_20171212_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatars/default.jpg', upload_to='avatars/upload/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('vacation', 'On Vacation')], default='online', help_text='Select a status for others to view', max_length=8),
        ),
    ]
